# Generated by Django 5.1.4 on 2025-01-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="muser",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
    ]
